FROM node:20-alpine

# Instalar pnpm de forma global dentro del contenedor
RUN npm install -g pnpm

WORKDIR /app

# Copiar el manifiesto y el candado real de pnpm
COPY package.json pnpm-lock.yaml ./

# Instalar las dependencias usando pnpm de forma estricta
RUN pnpm install --frozen-lockfile

COPY . .

EXPOSE 3000

CMD ["pnpm", "run", "dev"]
